/**
 * Arbitrum Stylus Registry Integration
 * Records chart creations on Arbitrum Sepolia using Stylus contracts
 * 
 * Benefits:
 * - 10-100x cheaper gas costs
 * - Faster execution
 * - Memory-safe Rust implementation
 */

import { ethers } from 'ethers';

// Contract ABI for Stylus ChartRegistry (generated by SDK)
const CHART_REGISTRY_ABI = [
  'function init() external',
  'function registerChart(string chartId, bytes32 chartHash, address user, bool zkVerified) external returns (bool)',
  'function registerChartWithZk(string chartId, bytes32 chartHash, address user, bytes32 commitment, bytes32 proof, bytes32 nonce, bytes32 positionsHash) external returns (bool)',
  'function verifyZkProofOnchain(bytes32 commitment, bytes32 proof, bytes32 nonce, bytes32 positionsHash) external view returns (bool)',
  'function verifyChart(string chartId, bytes32 chartHash) external view returns (bool)',
  'function getChartHash(string chartId) external view returns (bytes32)',
  'function getChartUser(string chartId) external view returns (address)',
  'function getChartTimestamp(string chartId) external view returns (uint256)',
  'function isZkVerified(string chartId) external view returns (bool)',
  'function markAsVerified(string chartId) external returns (bool)',
  'function totalCharts() external view returns (uint256)',
  'function chartExists(string chartId) external view returns (bool)',
  'function owner() external view returns (address)',
];

/**
 * Get Arbitrum contract instances
 */
function getArbitrumContracts() {
  const privateKey = process.env.AGENT_DEPLOYER_PRIVATE_KEY;
  const chartRegistryAddress = process.env.CHART_REGISTRY_ADDRESS;
  const rpcUrl = process.env.ARBITRUM_SEPOLIA_RPC || 'https://sepolia-rollup.arbitrum.io/rpc';
  const network = process.env.ARBITRUM_NETWORK || 'arbitrum-sepolia';

  if (!privateKey) {
    throw new Error('AGENT_DEPLOYER_PRIVATE_KEY not set');
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);

  const chartRegistry = chartRegistryAddress 
    ? new ethers.Contract(chartRegistryAddress, CHART_REGISTRY_ABI, wallet)
    : null;

  return { chartRegistry, wallet, provider, network };
}

/**
 * Generate keccak256-based ZK proof for on-chain verification
 */
function generateOnChainZKProof(
  chartData: any,
  nonce: string
): { commitment: string; proof: string; nonceHash: string; positionsHash: string } {
  // Create positions hash
  const positionsStr = JSON.stringify({
    planets: chartData.planets,
    asc: chartData.asc,
    mc: chartData.mc,
  });
  const positionsHash = ethers.keccak256(ethers.toUtf8Bytes(positionsStr));
  
  // Create commitment = keccak256(positionsHash || nonce)
  const commitmentInput = ethers.concat([
    ethers.toUtf8Bytes(positionsStr),
    ethers.toUtf8Bytes(nonce)
  ]);
  const commitment = ethers.keccak256(commitmentInput);
  
  // Pad nonce to 32 bytes
  const nonceHash = ethers.keccak256(ethers.toUtf8Bytes(nonce));
  
  // Create challenge = keccak256(commitment || positionsHash)
  const challengeInput = ethers.concat([commitment, positionsHash]);
  const challenge = ethers.keccak256(challengeInput);
  
  // Create proof = keccak256(commitment || nonceHash || challenge)
  const proofInput = ethers.concat([commitment, nonceHash, challenge]);
  const proof = ethers.keccak256(proofInput);
  
  return { commitment, proof, nonceHash, positionsHash };
}

/**
 * Record chart creation on Arbitrum Sepolia with ON-CHAIN ZK verification
 * 
 * @param chartId - Unique chart identifier
 * @param chartData - Chart data including positions
 * @param userId - User address (optional)
 * @param zkProof - ZK proof string (used as nonce for on-chain proof)
 * @param useOnChainZK - Whether to verify ZK proof on-chain (default: true)
 * @returns Transaction hash and chart hash
 */
export async function recordChartOnArbitrum(
  chartId: string,
  chartData: any,
  userId: string | null,
  zkProof: string,
  useOnChainZK: boolean = true
): Promise<{ txHash: string; chartHash: string; explorerUrl: string; zkVerifiedOnChain: boolean } | null> {
  try {
    const { chartRegistry, wallet, network } = getArbitrumContracts();

    if (!chartRegistry) {
      console.log('⚠️  Stylus Chart Registry not deployed, skipping on-chain record');
      return null;
    }

    console.log(`📝 Recording chart ${chartId} on Arbitrum Sepolia (Stylus)...`);

    // Create chart hash (commitment) - includes ZK proof
    const chartDataStr = JSON.stringify({
      planets: chartData.planets,
      asc: chartData.asc,
      mc: chartData.mc,
      zkProof,
    });
    const chartHash = ethers.keccak256(ethers.toUtf8Bytes(chartDataStr));

    // Determine user address (use deployer if anonymous)
    const userAddress = userId && userId.startsWith('0x')
      ? ethers.getAddress(userId) // If userId is an address
      : wallet.address; // Platform address for anonymous users

    console.log(`  Chart Hash: ${chartHash}`);
    console.log(`  User: ${userAddress}`);

    let tx;
    let zkVerifiedOnChain = false;

    if (useOnChainZK) {
      // Generate on-chain compatible ZK proof
      const { commitment, proof, nonceHash, positionsHash } = generateOnChainZKProof(chartData, zkProof);
      
      console.log(`  🔐 On-Chain ZK Verification Enabled`);
      console.log(`     Commitment: ${commitment.slice(0, 18)}...`);
      console.log(`     Proof: ${proof.slice(0, 18)}...`);

      // Register with on-chain ZK verification
      tx = await chartRegistry.registerChartWithZk(
        chartId,
        chartHash,
        userAddress,
        commitment,
        proof,
        nonceHash,
        positionsHash
      );
      zkVerifiedOnChain = true;
    } else {
      // Legacy: Register without on-chain ZK (server-verified)
      console.log(`  ZK Verified: true (server-side)`);
      tx = await chartRegistry.registerChart(
        chartId,
        chartHash,
        userAddress,
        true
      );
    }

    console.log(`  Transaction sent: ${tx.hash}`);
    const receipt = await tx.wait();
    console.log(`✅ Chart recorded on Arbitrum Sepolia (block ${receipt?.blockNumber})`);
    console.log(`  ⛽ Gas used: ${receipt?.gasUsed?.toString()}`);
    if (zkVerifiedOnChain) {
      console.log(`  🔐 ZK Proof verified ON-CHAIN!`);
    }

    // Get explorer URL
    const explorerUrl = network === 'arbitrum-one' 
      ? `https://arbiscan.io/tx/${tx.hash}`
      : `https://sepolia.arbiscan.io/tx/${tx.hash}`;

    return {
      txHash: tx.hash,
      chartHash,
      explorerUrl,
      zkVerifiedOnChain,
    };
  } catch (error: any) {
    console.error('❌ Failed to record chart on Arbitrum:', error.message);
    return null;
  }
}

/**
 * Verify a chart on-chain
 * 
 * @param chartId - Chart identifier
 * @param chartData - Chart data to verify
 * @param zkProof - ZK proof
 * @returns Whether the chart is valid
 */
export async function verifyChartOnArbitrum(
  chartId: string,
  chartData: any,
  zkProof: string
): Promise<boolean> {
  try {
    const { chartRegistry } = getArbitrumContracts();

    if (!chartRegistry) {
      return false;
    }

    // Recreate hash
    const chartDataStr = JSON.stringify({
      planets: chartData.planets,
      asc: chartData.asc,
      mc: chartData.mc,
      zkProof,
    });
    const chartHash = ethers.keccak256(ethers.toUtf8Bytes(chartDataStr));

    // Verify on-chain
    const isValid = await chartRegistry.verifyChart(chartId, chartHash);
    return isValid;
  } catch (error) {
    console.error('Error verifying chart on Arbitrum:', error);
    return false;
  }
}

/**
 * Get chart details from Arbitrum
 * 
 * @param chartId - Chart identifier
 * @returns Chart commitment details
 */
export async function getChartFromArbitrum(chartId: string) {
  try {
    const { chartRegistry } = getArbitrumContracts();

    if (!chartRegistry) {
      return null;
    }

    // Check if chart exists first
    const exists = await chartRegistry.chartExists(chartId);
    if (!exists) {
      return null;
    }

    // Get individual chart fields
    const [chartHash, user, timestamp, zkVerified] = await Promise.all([
      chartRegistry.getChartHash(chartId),
      chartRegistry.getChartUser(chartId),
      chartRegistry.getChartTimestamp(chartId),
      chartRegistry.isZkVerified(chartId),
    ]);
    
    return {
      chartHash,
      user,
      timestamp: Number(timestamp),
      zkVerified,
      chartId,
    };
  } catch (error) {
    console.error('Error getting chart from Arbitrum:', error);
    return null;
  }
}

/**
 * Get all charts for a user from Arbitrum
 * 
 * @param userAddress - User's Ethereum address
 * @returns Array of chart IDs
 */
export async function getUserChartsFromArbitrum(userAddress: string): Promise<string[]> {
  // Note: User chart listing not available in current contract
  // Charts are stored by chart_id, not user address
  // This would require off-chain indexing for full functionality
  console.log('getUserChartsFromArbitrum: User chart listing requires off-chain indexing');
  return [];
}

/**
 * Get total charts count from Arbitrum
 * 
 * @returns Total number of charts
 */
export async function getTotalChartsFromArbitrum(): Promise<number> {
  try {
    const { chartRegistry } = getArbitrumContracts();

    if (!chartRegistry) {
      return 0;
    }

    const total = await chartRegistry.totalCharts();
    return Number(total);
  } catch (error) {
    console.error('Error getting total charts from Arbitrum:', error);
    return 0;
  }
}

/**
 * Check if Arbitrum contracts are deployed
 */
export function areArbitrumContractsDeployed(): boolean {
  return !!process.env.CHART_REGISTRY_ADDRESS;
}

export default {
  recordChartOnArbitrum,
  verifyChartOnArbitrum,
  getChartFromArbitrum,
  getUserChartsFromArbitrum,
  getTotalChartsFromArbitrum,
  areArbitrumContractsDeployed,
};

